name: libc CI/CD on PRs

on:
  pull_request:
    branches:
      - staging

jobs:
  lib-libc-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run test script
        run: |
          bash ci/libc_tests/run_tests.sh
